services:
  - type: web
    name: fedsentinel-dashboard
    env: docker
    dockerfilePath: ./Dockerfile.dashboard
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: INBOX_PATH
        value: /data/inbox
    disk:
      name: fedsentinel-inbox
      mountPath: /data/inbox
      sizeGB: 1

  - type: worker
    name: fedsentinel-healer
    env: docker
    dockerfilePath: ./Dockerfile.healer
    plan: free
    autoDeploy: true
    envVars:
      - key: HEAL_INTERVAL_SECONDS
        value: "60"
    disk:
      name: fedsentinel-inbox
      mountPath: /data/inbox
      sizeGB: 1